### ISSUE TITLE
shortcuts for common queries

### ISSUE THREAD

**Issue by jhcepas** [etetoolkit/treematcher#6]
Some queries are very common. We should provide shortcut functions. Some candidates: 
contains_species(@, [a, b, c, ...]) 
contains(@, [a, b, c, ...])
number_of_species(@) 
is_duplication(@)  # checks node.evol_type inferred with PhyloTree.get_descendant_evol_events()
is_speciation(@) # checks 
size(@) 
New function TreePattern.has_match() → return true if the target tree has at least one match

**Comment by fransua** [comment]
@AlishaMechtley almost there, the actual syntax is like:

`@.contains([a, b, c, ...])`
and should be:
`contains(@, [a, b, c, ...])`

**Comment by AlishaMechtley** [comment]
What is the purpose of number_of_species(@)  and number_of_leaves(@) ? 
Do we want a function that allows the user to specify the number of species or leaves in a pattern (if so, there should be an extra parameter and it should return True or False like the rest), or do we want something to use internally that actually returns the number itself? I think the former makes more sense so I'll do that for now.

**Comment by AlishaMechtley** [comment]
I am uncertain how to create an is_duplication or is_speciation function. Currently I am doing the following:

1) Gather all the evol events using events = tree.get_descendant_evol_events()
events are: 
[<ete3.phylo.evolevents.EvolEvent instance at 0x10b4efbd8>, <ete3.phylo.evolevents.EvolEvent instance at 0x10b4ef320>, ... etc.])
2) get the event.evol_type for each one (e.g., 'D') 
3) create a list of duplications and check if the current target node is in the list??? How?

This is where I'm stuck. The target nodes are different from the evolution events and I'm not sure how to compare them since the numbers do not match. In other words,  I'm not sure how check if an EvolEvent node matches a PhyloTree node.
target nodes are:
PhyloTree node '' (0x10b4e29d)
PhyloTree node '' (0x10b4e2a1)
... etc.
